#!/usr/bin/env bash
# Will display info about subdomain

info () {
    _1=$(dig $2.$1 | awk '/ANSWER SECTION:/{getline;print;}')
    RT=$(echo $A | cut -d' ' -f 4)
    DEST=$(echo $A | cut -d' ' -f 4)
    echo "The subdomain $2 is a $RT record and points to $DEST"
}
if [ $# -lt 1 ]
then
    echo "Usage: 1-world_wide_web DOMAIN SUBDOMAIN(optional)"
elif [ $# -eq 1 ]
then
    info "$1" "www"
    info "$1" "lb-01"
    info "$1" "web-01"
    info "$1" "web-02"
else
    info "$1" "$2"
fi
