#!/usr/bin/env bash
# Config a custom http response
sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
new_string="\\\trewrite ^/redirect_me https://www.google.com/ permanent;"
header="\t\tadd_header X-Served-By '$HOSTNAME';"
str="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart
