#!/usr/bin/env bash
# Config a custom http response
sudo apt-get update -y
sudo apt-get install nginx -y
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart