#!/usr/bin/env bash
# Config a custom http response
sudo apt-get update -y
sudo apt-get install nginx -y
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx reload
sudo service nginx restart
