#!/usr/bin/env bash
# Config  HAproxy on your lb-01 server.
sudo apt-get update -y
apt-get install -y haproxy
sudo sed -i "\$ a\listen 1561-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 1561-web-01 35.196.86.108:80 check\n\tserver 1561-web-02 34.75.109.142:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
