#!/usr/bin/env bash
# Config  HAproxy on your lb-01 server.
sudo apt-get update -y
apt-get install -y haproxy

CONFIG="\
frontend main
	 bind *80
	 mode http
	 default_backend web-server

backend web-server
	balance roundrobin
	server 1561-web-01 35.196.86.108:80 check
	server 1561-web-02 34.75.109.142:80 check
"

sudo echo "$CONFIG" >> /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start