#!/usr/bin/env bash
# Config  HAproxy on your lb-01 server.
sudo apt-get update -y
sudo apt-get install -y haproxy

echo "frontend holberton_front
     bind *:80
     mode http
     default_backend holberton_back

backend holberton_back
	balance roundrobin
	server 1561-web-01 35.196.86.108:80 check
	server 1561-web-02 34.75.109.142:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart