#!/usr/bin/env bash
# bash that creates a mysql dump
if [ $# -gt 0 ]
then
	PWD=$1
else
	PWD=""
fi

user="root"

mysqldump --all-databases --user=$USER --password=$PWD > backup.sql
DATE=$(date +"%d-%m-%Y")
tar -czf "$DATE".tar.gz backup.sql
